### ISSUE TITLE
Fix access to MEP algo

### ISSUE THREAD

**Issue by hrbonz** [hrbonz/python-aqi#1]
Right now, the mep algorithm is written but not accessible as it's missing in `aqi.constants`

**Comment by Marvin-liu** [comment]
Excuse me, I really want to whether I can use "algo=ALGO_MEP" in the function "aqi.to_aqi" in version 5.0.1. Thank you!

**Comment by hrbonz** [comment]
Hi, I just updated the package. Long overdue!! You can now `pip install python-aqi==0.5.1`

Closed by e9ab54796d548fa76147bdd3bb56881d0ffdb615
