### ISSUE TITLE
Convert an IAQI to its pollutant concentration

### ISSUE THREAD

**Issue by Santy99ab** [hrbonz/python-aqi#3]
`import aqi
mycc = aqi.to_cc(aqi.POLLUTANT_PM25, '22', algo=aqi.ALGO_EPA)`

It seems there isn't any implementation of aqi.to_cc in this library.

**Comment by vipulgupta2048** [comment]
True that 
``
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'aqi' has no attribute 'to_cc'
``
